### ISSUE TITLE
unintroduced terminology (vector)

### ISSUE THREAD

**Issue by ar-ora** [PsyTeachR/quant-fun-v3#7]
see https://github.com/PsyTeachR/quant-fun-v3/pull/5 (commit https://github.com/PsyTeachR/quant-fun-v3/pull/5/commits/da99e651016d7ffebc5bb4f3b2f06955811b808b) for details and a suggestion

**Comment by BartlettJE** [comment]
I've added a drop-down box explaining vectors if people are curious.
